name: "🤖 GUT tests"
on: [push, pull_request]

env:
  GODOT_VERSION: 3.4
  EXPORT_NAME: test-project

jobs:
  export-windows:
    name: GUT tests
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Run tests
        run: |
          godot --debug-collisions --path $PWD -d -s addons/gut/gut_cmdln.gd
